apiVersion: apps/v1
kind: Deployment
metadata:
  name: elgg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elgg-app
  template:
    metadata:
      labels:
        app: elgg-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: gke-elgg-cluster-default-pool-613e100a-jnqh
      securityContext:
        fsGroup: 33
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /var/www/elgg/data && chown -R 33:33 /var/www/elgg /var/elgg_data && chmod -R 755 /var/www/elgg && chmod -R 775 /var/elgg_data && ln -sfn /var/elgg_data /var/www/elgg/data && ls -la /var/www/elgg"]
        #fichiers de configuration
        # command: ["/bin/sh", "-c", "chown -R 33:33 /var/www/html/elgg/elgg-config && chmod -R 775 /var/www/html/elgg/elgg-config"]
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data
        - mountPath: /var/www/elgg
          name: app-code

        # - mountPath: /var/www/html/elgg/elgg-config
        #   name: elgg-config-volume

      containers:
      - name: elgg-app
        image: bitaouioussama/elgg-app:v7
        imagePullPolicy: Always
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          capabilities:
            add: ["NET_BIND_SERVICE"]
        envFrom:
          - secretRef:
              name: elgg-env
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "800m"
            memory: "700Mi"
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data
        - mountPath: /var/www/elgg
          name: app-code

        # - mountPath: /var/www/html/elgg/elgg-config
        #   name: elgg-config-volume

      volumes:
      - name: elgg-data
        persistentVolumeClaim:
          claimName: elgg-pvc
      - name: app-code
        emptyDir: {}
      # - name: elgg-config-volume
      #   persistentVolumeClaim:
      #     claimName: elgg-config-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: elgg-app
spec:
  type: LoadBalancer
  selector:
    app: elgg-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 34.175.206.89
